delimiter ;
CREATE TABLE `events_member` (
  `memberid` varchar(50) NOT NULL DEFAULT '',
  `email` varchar(255) NOT NULL,
  `email_confirmed` tinyint(4) DEFAULT 0,
  `member_firstname` varchar(255) DEFAULT '',
  `member_lastname` varchar(255) DEFAULT '',
  `member_street` varchar(255) DEFAULT '',
  `member_zipcode` varchar(255) DEFAULT '',
  `member_town` varchar(255) DEFAULT '',
  `emailtoken` varchar(64) DEFAULT NULL,
  `kostenstelle` int(11) DEFAULT 0,
  `accesscontroll` tinyint(4) DEFAULT 0,
  `preiskategorie` int(11) DEFAULT 0,
  `aktiv` tinyint(4) DEFAULT 1,
  `request_retry` int(11) DEFAULT 0,
  `createat` timestamp NOT NULL DEFAULT current_timestamp(),
  `ridx` varchar(255) DEFAULT NULL,
  `insert_date` date DEFAULT NULL,
  `insert_time` time DEFAULT NULL,
  `update_time` time DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `login` varchar(255) DEFAULT NULL,
  `update_date` varchar(255) DEFAULT NULL,
  `member_phone` varchar(255) DEFAULT '',
  PRIMARY KEY (`memberid`),
  UNIQUE KEY `uidx_events_members_email` (`email`),
  KEY `idx_events_member` (`memberid`,`kostenstelle`)
);